### ISSUE TITLE
Add a scala package to include scala utility classes and methods

### ISSUE THREAD

**Issue by t-ober** [ie3-institute/PowerSystemUtils#133]
- add Scala support - Scala 3? - check for compatibility issues

- @t-ober add QuantityUtils 
- @johanneshiry check SIMONA for stuff to transfer

**Comment by johanneshiry** [comment]
We should also add the following code in `build.gradle` to make the main branch build again:

```
tasks.withType(Javadoc){
	options.encoding = 'UTF-8'
}
```
