### ISSUE TITLE
Allow reading of `ZonedDateTime`

### ISSUE THREAD

**Issue by t-ober** [ie3-institute/PowerSystemUtils#306]

**Comment by t-ober** [comment]
This is related to: https://github.com/ie3-institute/PowerSystemDataModel/issues/766

If we fix that one this issue is solved. Reading only was a problem due to unconventional time stamp patterns due to persisting via `toString`

**Comment by sebastian-peter** [comment]
@t-ober Is this fixed with #416?

**Comment by t-ober** [comment]
Yes that should be fixed
