### ISSUE TITLE
Comparison between Quantities does not work as expected

### ISSUE THREAD

**Issue by t-ober** [ie3-institute/PowerSystemUtils#348]
When comparing Quantities that are created with the `DoubleConverterFactory` and ones created "the regular way" we get unexpected failures.

That seems to be because the Units differ in their details.

e.g. the following test fails:

```
    def "creates units that are comparable to standard Quantity creation"() {

        when:
        def a = Quantities.getQuantity(1.234, PowerSystemUnits.NANOSIEMENS)
        def b = Quantities.getQuantity(1.234, MetricPrefix.NANO(Units.SIEMENS))

        then:
        a == b
    }
```

**Comment by t-ober** [comment]
Related: https://github.com/ie3-institute/simBench2psdm/issues/138

**Comment by sebastian-peter** [comment]
As discussed, there is no easy solution to this besides just using the units in `PowerSystemUnits`. These also have the advantage that they can speed up calculations with quantities.
