### ISSUE TITLE
Adapt implementation of unit PU

### ISSUE THREAD

**Issue by ckittl** [ie3-institute/PowerSystemUtils#39]
As of now, the unit `PU` is defined as a transformed unit from `PERCENT` (multiply by 100 to get to %) - see below.

https://github.com/ie3-institute/PowerSystemUtils/blob/5cbef5cab41f50d073233aac1aa3adf4b1081bd9/src/main/java/edu/ie3/util/quantities/PowerSystemUnits.java#L40-L41

However, `PERCENT` is also a transformed unit from `one` (divide by 100 to get to 1). Therefore, PU is more a alternative unit, then a transformed unit:

`public static final Unit<Dimensionless> PU = new AlternateUnit<>(one, "PU");`

This causes issues, when you divide two quantities with the same unit (then it gets the unit `one`).

**Comment by johanneshiry** [comment]
Just for clarification as I don't get it: 

1. The implementation you're pointing to is a 1:1 copy of the existing implementation right? I compared the old and the new implementation and both are the same. The old implementation was working correctly wasn't it?

2. Is this `public static final Unit<Dimensionless> PU = new AlternateUnit<>(one, "PU");` your proposal how to implement `PU` from now on? And if yes, is this proposal causing the issues you're pointing to? Or is the old implementation causing issues? If the new implementation is causing issues is keeping the old one a way to go?
