### ISSUE TITLE
Take over methods from other projects that fit better in here

### ISSUE THREAD

**Issue by ckittl** [ie3-institute/PowerSystemUtils#56]
- PowerSystemDataModel
  - [x] `GridAndGeoUtils#buildSafeLineString`
  - [x] `GridAndGeoUtils#buildSafeLineStringBetweenCoords`
  - [x] `GridAndGeoUtils#buildSafeLineStringBetweenPoints`
  - [x] `GridAndGeoUtils#buildSafeCoord`
  - [x] `GridAndGeoUtils#buildSafePoint`
  - [x] `GridAndGeoUtils#getCoordinateDistances`
- NetPadPlusPlus
  - [x] `GridController#lengthOfLineString`

**Comment by mia-krause** [comment]
- SIMONA
   - [ ] SampleWeatherSource#ToNextFull
